/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Form: typeof import('./src/components/Form.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListUsers: typeof import('./src/components/ListUsers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateValueForm: typeof import('./src/components/UpdateValueForm.vue')['default']
    UserListLine: typeof import('./src/components/UserListLine.vue')['default']
  }
}
